### ISSUE TITLE
Exception and weird map

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#161]
With the Heroku deployment, to reproduce:
- Choose the first two studies of both PanCancer Studies and Cell lines
- Choose Prostate Cancer AR signaling (10 genes)
- See the PM tab:
![image](https://user-images.githubusercontent.com/3874988/60894827-1f7d8c00-a26c-11e9-8602-f88d7a8b80b9.png)
- We also get an exception in the Console:
/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92 Uncaught DOMException: Failed to execute 'drawImage' on 'OffscreenCanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at y.safeDrawImage (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:172117)
    at y.drawInscribedImage (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:173916)
    at H (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:180654)
    at y.drawNode (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:181909)
    at y.drawElement (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:165836)
    at Aa.drawElement (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:199509)
    at Aa.xa.getElement (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:156764)
    at y.drawCachedElementPortion (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:166096)
    at y.Ba.drawCachedElement (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:167147)
    at y.Ba.drawCachedElements (https://cbio-pm.herokuapp.com/reactapp/7.6a4a10eed6758bb6a3b6.chunk.js:92:167549)

**Comment by ugurdogrusoz** [comment]
I experienced the above problem with Chrome (Windows 10 home). Seems to be OK on Firefox.
