### ISSUE TITLE
Collaborative mode seems broken

### ISSUE THREAD

**Issue by onursumer** [iVis-at-Bilkent/pathway-mapper#279]
A mongoDB error in the client console when switched to the collaborative mode:

```
caught Error: Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
    at g (connection.js:266:13)
    at f.handleMessage (connection.js:178:11)
    at t.onmessage (connection.js:134:18)
```

On the server side a similar mongoDB error:

```
MongoError: Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
    at Function.MongoError.create (/pathway-mapper/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/pathway-mapper/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /pathway-mapper/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

I tried upgrading the ShareDB version to the latest but it didn't seem to fix the issue.

**Comment by ugurdogrusoz** [comment]
This might be related to MongoDB version being outdated.

**Comment by ugurdogrusoz** [comment]
Is this fixed now @YusufZiyaOzgul ?

**Comment by YusufZiyaOzgul** [comment]
it is fixed now. I close the issue.

**Comment by YusufZiyaOzgul** [comment]
Issue is fixed now. I close the issue.
