### ISSUE TITLE
What node/npm version is required?

### ISSUE THREAD

**Issue by inodb** [iVis-at-Bilkent/pathway-mapper#61]
Following instructions from the README, I get the following error:

```
$ npm start

> @0.0.0 start /Users/debruiji/git/pathway-mapper
> node app.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Server._listen2 (net.js:1237:19)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventEmitter.listen (/Users/debruiji/git/pathway-mapper/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/debruiji/git/pathway-mapper/app.js:197:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE
npm ERR! @0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/debruiji/git/pathway-mapper/npm-debug.log
```

**Comment by istemi-bahceci** [comment]
@inodb 

Seems 'sudo' was missing before 'npm start'. Updated readme accordingly. Thanks for reporting.

**Comment by inodb** [comment]
@istemi-bahceci Thanks that worked! The default port is actually 80 (README says 3000), which is why you need `sudo`.
